x-variables:
  - &codebase codebase:/var/www/html

services:

  php:
    build: context
    environment:
      DRUPAL_TRUSTED_HOST_PATTERNS: '^staging.embassy.science$$'
      PHP_SENDMAIL_PATH: '"/usr/bin/dos2unix -u | /usr/sbin/ssmtp -t -f"'
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - *codebase

  crond:
    image: wodby/drupal:7-8.0
    environment:
      CRONTAB: "0 * * * * drush -r /var/www/html/web cron"
      PHP_FPM_CLEAR_ENV: "no"
    command: sudo -E crond -f -d 0
    volumes:
      - *codebase

  nginx:
    image: wodby/nginx:1.23-5.30.4
    depends_on:
      - php
    ports:
      - 8080:80
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      # Erst, wenn der nginx den h5p-Link nimmt:
      # NGINX_SERVER_ROOT: /var/www/html/root
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: drupal7
    volumes:
      - *codebase

  mariadb:
    image: wodby/mariadb:10.9-3.24.3
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - mysql:/var/lib/mysql
    
volumes:
  codebase:
  mysql:
